### ISSUE TITLE
Add safety features to prevent accidental deletion of running functions

### ISSUE THREAD

**Issue by jlhood** [lumigo/SAR-Lambda-Janitor#1]
Very cool app! I'm concerned that the initial version of this app is too aggressive in which function versions get deleted. If I'm reading the code correctly, it looks like the only function versions it won't delete are ones that have an alias pointing at them. However, not everyone uses aliases on their functions so the app could delete a function that's serving customer traffic, causing an outage. The safety feature I've seen added to similar apps is to have a configurable minimum number of versions to keep for a given function. Keeping the newest n versions of the function around usually provides a sufficient safety net.

**Comment by theburningmonk** [comment]
That's a good shout. Hadn't thought about that, assumed people are either using `$Latest` or at least some alias. This change would be easy to add, but still wouldn't prevent guarantee we don't delete a live version since there's no telling what's being used.

Can you share some examples of how people are managing functions in prod without aliases?

**Comment by jlhood** [comment]
I'm not sure if `Lambda.listAliasedVersions()` is the same thing as Lambda's [ListAliases](https://docs.aws.amazon.com/lambda/latest/dg/API_ListAliases.html) API, but when I test calling ListAliases on a function, it doesn't return $LATEST. That's my main concern. If your code isn't receiving $LATEST back from `Lambda.listAliasedVersions()`, then the alias check won't save the latest version from being deleted unless you're explicitly using aliases, e.g., traffic shifting.

There are several use cases where I don't use aliases. For example, on async processing Lambda functions, I don't usually choose to use traffic shifting. I think one of the core use cases of using aliases is to point to different versions of a function for beta vs prod. However, a better practice is to use entirely different accounts for beta and prod, in which case, you don't need to use aliases, because beta and prod are different functions.

Here is [another SAR app](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:414864144042:applications~lambda-versions-deleter) that does something similar to yours. It is deleting all but the last n versions, but it doesn't have the alias guard that yours has. Also, you have to deploy the app once per Lambda function whereas your app manages deleting old versions on all Lambda functions in the region, which is pretty convenient.

**Comment by jlhood** [comment]
Oh sorry, totally missed [this file](https://github.com/lumigo/SAR-Lambda-Janitor/blob/master/functions/lib/lambda.js#L63)! Yeah so you're using the ListAliases API which doesn't return $LATEST as an alias.

**Comment by jlhood** [comment]
And now I see [this](https://github.com/lumigo/SAR-Lambda-Janitor/blob/master/functions/lib/lambda.js#L39) as well. Ok I didn't realize you were proactively excluding $LATEST from your returned list. That resolves my concern about this app deleting $LATEST. But it's still a good idea to keep the latest n versions so glad to see that PR.

**Comment by theburningmonk** [comment]
@jlhood do you have any more concerns around guardrails that are needed?

**Comment by theburningmonk** [comment]
Closing for now since it's been quiet for some time.

**Comment by jlhood** [comment]
Sorry for the delayed response on this. I think what you have right now is sufficient for most use cases. However, there is one more advanced safety check that would be a terrific feature to add (and make this app by far the most recommended one to use for cleaning up old Lambda function versions).

You can add a feature to avoid deleting Lambda function versions that have been invoked within the last X days (configurable). Your app can determine this by calling the CloudWatch API and pulling metric data for function version invocations. When Lambda function versioning is enabled, the Lambda service provides metrics for invocation counts per function version (you can find this in the CloudWatch console under Metrics -> Lambda namespace -> click "By Executed Version" (you may only see this if you have versioning/aliases enabled and have invoked a function version through its alias).

Again, not a hard requirement, but I think adding this would make this app very advanced.

**Comment by theburningmonk** [comment]
Thanks @jlhood that's a good shout! I'm gonna open a separate issue for that.
