### ISSUE TITLE
"Rate Limit Exceeded" on 300+ functions

### ISSUE THREAD

**Issue by jfxdev** [lumigo/SAR-Lambda-Janitor#13]
Hello!

I'm face some problems when running Janitor on environments that have 300+ functions, and getting "Rate Limit Exceeded" on lambda API. There's a way to make the scanner run syncronous or more slower on large environments?

Thanks!

**Comment by theburningmonk** [comment]
@jfxdev try the new version 1.3.0, I added better error handling, hopefully that fixes the problem for you!

**Comment by keremgocen** [comment]
This is still an issue with 100+ dangling functions, the current AWS lambda concurrency limit being 100.
`"errorName":"TooManyRequestsException","errorMessage":"Rate exceeded","stackTrace":"TooManyRequestsException: Rate exceeded\n`
Could be useful to have a patch where we provide the max number for concurrency as a runtime argument.
