### ISSUE TITLE
Upgrade Lambda runtime to nodejs10.x

### ISSUE THREAD

**Issue by jlhood** [lumigo/SAR-Lambda-Janitor#15]
This app is written using nodejs8.10 Lambda function runtime, but that's approaching [end of life](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html). Can you upgrade the app to nodejs10.x?

**Comment by jlhood** [comment]
Thanks!

**Comment by theburningmonk** [comment]
No probs :-) Thanks for prodding
